allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects { p ->
    if (p.name != "app") {
        p.ext.flutter = [
            compileSdkVersion: 35,
            minSdkVersion: 21,
            targetSdkVersion: 35
        ]
    }
    p.plugins.withId("com.android.library") {
        p.android {
            compileSdkVersion 35
        }
    }
    p.plugins.withId("com.android.application") {
        p.android {
            compileSdkVersion 35
        }
    }
}




subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}


