// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjAeNNDh7kdggBbavnsChPeorDOI2KsQo',
    appId: '1:572019055251:android:ceeff43eeb02548f1a0b66',
    messagingSenderId: '572019055251',
    projectId: 'uxportal-6b259',
    storageBucket: 'uxportal-6b259.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzJF2YBRUKdPSBO_s6Hxs8WDUvjUYiYCk',
    appId: '1:572019055251:ios:251436baa552d15b1a0b66',
    messagingSenderId: '572019055251',
    projectId: 'uxportal-6b259',
    storageBucket: 'uxportal-6b259.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArzSRyajwKmBem-atRBa4NXDMO5jP8OtY',
    appId: '1:572019055251:web:a4817b9d9f914f901a0b66',
    messagingSenderId: '572019055251',
    projectId: 'uxportal-6b259',
    authDomain: 'uxportal-6b259.firebaseapp.com',
    storageBucket: 'uxportal-6b259.firebasestorage.app',
    measurementId: 'G-G80M21L533',
  );
}
